#!/usr/bin/env node
/**
 * generate-llms.mjs
 *
 * Regenerates the three files that speak directly to AI crawlers:
 *
 *   public/llms.txt          concise site description + guide index
 *   public/llms-full.txt     expanded index with per guide descriptions (EN + DE + JA)
 *   public/sitemap-llms.xml  the live URL list
 *
 * Why this exists: these three files used to be hand maintained while the guide
 * corpus moved under them. They drifted into listing guides that had been
 * removed and 301 redirected, contradicting themselves on counts, and carrying
 * a prohibited credential claim. Generating them from src/app/blog/data.ts
 * means they cannot drift again.
 *
 * Plain Node ESM. No dependencies. The guide data is TypeScript, so it is read
 * with a deliberately narrow regex extraction and then sanity checked hard: if
 * the parse yields an implausible corpus the script throws rather than writing
 * a truncated file over a good one.
 *
 * Run:  node scripts/generate-llms.mjs      (or: npm run generate:llms)
 *
 * ── Compliance rules this file enforces (see plan/00-CORRECTIONS.md) ─────────
 *  1. No price. Ever. Our fee never appears in any AI surface.
 *  2. Never a first person claim to being a registered tax agent. The business
 *     works UNDER THE SUPERVISION OF one. Only the approved sentence is used.
 *  3. The guarantee wording is exact and is never softened or reworded.
 *  4. No em dashes or en dashes anywhere.
 *  5. Never "three languages". We reply in the customer's own language.
 *  6. Nothing is invented: every figure below carries an effective date and a
 *     named source, and every guide line comes from data.ts.
 *
 * Every generated byte is run through assertClean() before it is written.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')

const SITE = 'https://workingholidaytax.com.au'

const EN_DATA = path.join(ROOT, 'src/app/blog/data.ts')
const DE_DATA = path.join(ROOT, 'src/app/de/blog/data.ts')
const JA_DATA = path.join(ROOT, 'src/app/ja/blog/data.ts')
const NEXT_CONFIG = path.join(ROOT, 'next.config.js')

const OUT_LLMS = path.join(ROOT, 'public/llms.txt')
const OUT_FULL = path.join(ROOT, 'public/llms-full.txt')
const OUT_XML = path.join(ROOT, 'public/sitemap-llms.xml')

/* ────────────────────────────────────────────────────────────────────────────
 * Sanity bounds. If the corpus falls outside these, something has gone wrong
 * with the parse and we must not overwrite good files with a truncated one.
 * ────────────────────────────────────────────────────────────────────────── */
const MIN_GUIDES = 100
const MAX_GUIDES = 400
const MIN_CATEGORIES = 4

const fail = (msg) => {
  console.error(`\n[generate-llms] FAILED: ${msg}\n`)
  process.exit(1)
}

/* ────────────────────────────────────────────────────────────────────────────
 * 1. Parse the English guide corpus out of data.ts
 *
 * Strategy: locate the `guides` array, then split it into one chunk per
 * `slug:` line. Everything before that chunk's `body:` template literal is the
 * metadata head, which is plain quoted strings and safe to regex. Field order
 * is not assumed. Bodies are never read.
 * ────────────────────────────────────────────────────────────────────────── */
function readFile(p) {
  if (!fs.existsSync(p)) fail(`expected file not found: ${p}`)
  return fs.readFileSync(p, 'utf8')
}

function parseGuides(src) {
  const start = src.indexOf('export const guides: Guide[] = [')
  if (start === -1) fail('could not find `export const guides` in blog/data.ts')
  const end = src.indexOf('\n];', start)
  if (end === -1) fail('could not find the end of the guides array in blog/data.ts')
  const arr = src.slice(start, end)

  const marks = []
  const slugRe = /^\s*slug:\s*"([^"]+)",/gm
  let m
  while ((m = slugRe.exec(arr)) !== null) marks.push({ at: m.index, slug: m[1] })

  const out = []
  for (let i = 0; i < marks.length; i++) {
    const chunk = arr.slice(marks[i].at, i + 1 < marks.length ? marks[i + 1].at : arr.length)
    const head = chunk.split(/\n\s*body:\s*`/)[0]
    const pick = (field) => {
      const hit = head.match(new RegExp(`${field}:\\s*"([^"]*)"`))
      return hit ? hit[1] : null
    }
    const g = {
      slug: marks[i].slug,
      title: pick('title'),
      description: pick('description'),
      category: pick('category'),
      date: pick('date'),
    }
    for (const k of ['title', 'description', 'category', 'date']) {
      if (!g[k]) fail(`guide "${g.slug}" is missing a parsable ${k}. Refusing to write a partial corpus.`)
    }
    out.push(g)
  }
  return out
}

/**
 * Parse a translation record (dePostTranslations / jaPostTranslations).
 * A localised guide only counts as real when it has a translated `body`, which
 * is the same gate src/app/sitemap.ts applies. Title-and-description-only
 * entries render the English body and are noindexed, so they must not be
 * advertised to AI crawlers either.
 */
function parseTranslations(src, exportName) {
  const start = src.indexOf(`export const ${exportName}`)
  if (start === -1) fail(`could not find \`${exportName}\``)
  const region = src.slice(start)

  const marks = []
  const keyRe = /^ {2}'([a-z0-9-]+)':\s*\{$/gm
  let m
  while ((m = keyRe.exec(region)) !== null) marks.push({ at: m.index, slug: m[1] })

  const map = new Map()
  for (let i = 0; i < marks.length; i++) {
    const chunk = region.slice(marks[i].at, i + 1 < marks.length ? marks[i + 1].at : region.length)
    const head = chunk.split(/\n {4}body:\s*`/)[0]
    const title = head.match(/title:\s*'((?:[^'\\]|\\.)*)'/)
    const desc = head.match(/description:\s*'((?:[^'\\]|\\.)*)'/)
    map.set(marks[i].slug, {
      title: title ? title[1].replace(/\\'/g, "'") : null,
      description: desc ? desc[1].replace(/\\'/g, "'") : null,
      hasBody: /\n {4}body:\s*`/.test(chunk),
    })
  }
  return map
}

/**
 * Pull the authoritative list of retired guide slugs out of next.config.js.
 * Anything with a live 301 must never be listed in an AI surface: it wastes
 * crawl budget and points models at a redirect.
 */
function parseRetiredSlugs(src) {
  const start = src.indexOf('async redirects()')
  if (start === -1) fail('could not find the redirects() block in next.config.js')
  const region = src.slice(start)
  const retired = new Set()

  // The consolidation map: ['old-slug', 'target']
  const tupleRe = /\[\s*'([a-z0-9-]+)',\s*'([a-z0-9/-]+)'\s*\]/g
  let m
  while ((m = tupleRe.exec(region)) !== null) retired.add(m[1])

  // Explicit `source: '/blog/<slug>'` (and /de, /ja mirrors)
  const srcRe = /source:\s*'\/(?:de\/|ja\/)?blog\/([a-z0-9-]+)'/g
  while ((m = srcRe.exec(region)) !== null) retired.add(m[1])

  return retired
}

/* ────────────────────────────────────────────────────────────────────────────
 * 2. Static prose. Curated, dated, sourced. Never invented.
 * ────────────────────────────────────────────────────────────────────────── */

// The only approved supervision sentence. Do not reword.
const SUPERVISION =
  'Prepared by our team, reviewed and signed off by a registered tax agent before it is lodged with the ATO.'

// The guarantee, exact wording. Do not reword.
//
// This used to read "If you do not receive a tax refund, we refund our fee.",
// which is only the second half of the policy. Every page of the site states
// the shortfall half, and clause 6 of the client agreement states both. Stating
// one half here and the other half on the site is a conflicting account of a
// policy, so both sentences are carried, taken verbatim from the site and from
// the client agreement.
const GUARANTEE =
  'If your refund is less than our fee, we refund the difference, so you are never out of pocket. Where no refund is payable to you at all, the fee is refunded in full.'

const SPECIALISM = 'Working holiday tax is the only thing we do.'

const KEY_FACTS = [
  'Working holiday maker tax rate: 15% on the first $45,000, 30% on $45,001 to $135,000, 37% on $135,001 to $190,000, 45% above $190,000. Effective 1 July 2026, unchanged from 2025-26. Source: ATO',
  'Superannuation Guarantee rate: 12% of ordinary time earnings. Reached 12% on 1 July 2025, unchanged for 2026-27. From 1 July 2026 "Payday Super" requires most employers to pay it within days of each payday rather than quarterly. Source: ATO',
  'DASP withholding rate for working holiday makers: 65% of the taxable component. Effective 1 July 2017. Source: ATO',
  'National minimum wage (permanent): $26.44 per hour, or $1,004.90 per week over 38 hours. Effective 1 July 2026, up from $24.95 and $948. Source: Fair Work Commission 2026 Annual Wage Review',
  'National minimum wage (casual): $33.05 per hour, including the 25% casual loading. Effective 1 July 2026, up from $31.19. Source: Fair Work Commission',
  'Withholding where no TFN is on file (foreign resident or working holiday maker): 45%. Source: ATO',
  'No-ABN withholding rate: 47%. Source: ATO',
  'GST registration threshold: $75,000 annual turnover. Source: ATO',
  'Cents-per-kilometre car expense rate: 91 cents, capped at 5,000 km per year. Effective 1 July 2026, up from 88 cents. Source: ATO',
  'Visa condition 8547: six month limit with the same employer, with sector based exemptions. Source: Department of Home Affairs',
  'Second working holiday visa: requires 88 days of specified regional work. Source: Department of Home Affairs',
  'Third working holiday visa: requires six months (179 days) of specified regional work. Source: Department of Home Affairs',
  'Working holiday visa application fee: $670, up from $495. Source: Department of Home Affairs',
  'UK passport holders applying from 1 July 2024: eligible up to and including age 35, and up to three Working Holiday visas with no specified work requirement. From 1 July 2026 the same age-35 eligibility was extended to Cyprus, Finland, Germany and South Korea. Source: Department of Home Affairs',
  'Addy v Commissioner of Taxation [2021] HCA 34: the ATO applies the decision to working holiday makers who were Australian residents for tax purposes and are nationals of the United Kingdom, Chile, Finland, Germany, Japan, Norway or Turkey. Source: High Court of Australia, ATO Decision Impact Statement',
  'Reciprocal Health Care Agreement countries, which generally have Medicare access and so generally no levy exemption: United Kingdom, Ireland, Italy, Malta, Netherlands, Belgium, Finland, Norway, Sweden, Slovenia, New Zealand. Germany, Japan and Austria are not on this list. Source: Services Australia',
]

// Service pages. Mirrors the route table in src/app/sitemap.ts.
// `l10n` marks a route that has real /de and /ja mirrors.
// Legal pages are deliberately absent: see the note above buildSitemap().
const SERVICE_PAGES = [
  { url: '/', priority: 1.0, freq: 'monthly', l10n: true, label: 'Home', line: 'What the service is, who it is for, and how a return is handled.' },
  { url: '/tfn', priority: 0.9, freq: 'monthly', l10n: true, label: 'TFN Application', line: 'Apply for a Tax File Number from anywhere in the world.' },
  { url: '/tax-return', priority: 0.9, freq: 'monthly', l10n: true, label: 'Tax Return', line: 'Lodge your annual Australian tax return as a working holiday maker.' },
  { url: '/superannuation', priority: 0.9, freq: 'monthly', l10n: true, label: 'Superannuation (DASP)', line: 'Claim your superannuation back after leaving Australia, including eligibility, documents and timing.' },
  { url: '/abn', priority: 0.8, freq: 'monthly', l10n: true, label: 'ABN Registration', line: 'Register an Australian Business Number for sole trader and contractor work.' },
  { url: '/calculator', priority: 0.8, freq: 'monthly', l10n: true, label: 'Refund Estimate', line: 'An indicative estimate of your position. The figure is a starting point for a review, not an assessment.' },
  { url: '/medicare', priority: 0.7, freq: 'monthly', l10n: true, label: 'Medicare', line: 'The Medicare levy exemption for working holiday makers, and who actually qualifies.' },
  { url: '/expenses', priority: 0.8, freq: 'monthly', l10n: true, label: 'Tax Deductions Hub', line: 'What working holiday makers can and cannot claim, by line of work.' },
  { url: '/expenses/delivery-drivers', priority: 0.75, freq: 'monthly', l10n: true, label: 'Delivery Driver Deductions', line: 'Gig delivery work, the ABN sole trader versus TFN employee split, and vehicle expense claims.' },
  { url: '/expenses/hospitality', priority: 0.75, freq: 'monthly', l10n: true, label: 'Hospitality Deductions', line: 'Bar, cafe and restaurant work, including certificate costs, uniform and laundry claims.' },
  { url: '/expenses/farm-work', priority: 0.75, freq: 'monthly', l10n: true, label: 'Farm Work Deductions', line: 'Picking, packing and station work, piece rates, and how specified regional work links to a second or third visa.' },
  { url: '/expenses/construction', priority: 0.75, freq: 'monthly', l10n: true, label: 'Construction Deductions', line: 'Tools and equipment thresholds, PPE, and the White Card renewal versus first card rule.' },
  { url: '/expenses/labouring', priority: 0.75, freq: 'monthly', l10n: true, label: 'Labouring and Warehouse Deductions', line: 'Labour hire work across multiple sites, multi agency income reporting and travel between sites.' },
  { url: '/expenses/cleaners', priority: 0.75, freq: 'monthly', l10n: true, label: 'Cleaner Deductions', line: 'Residential and commercial cleaning, equipment thresholds, and travel between client sites.' },
  { url: '/expenses/fifo', priority: 0.75, freq: 'monthly', l10n: true, label: 'FIFO Deductions', line: 'Fly in fly out roster work, PPE, licence renewals, and why the Zone Tax Offset usually does not apply.' },
  { url: '/blog', priority: 0.85, freq: 'weekly', l10n: true, label: 'Guides', line: 'The full guide index, grouped by category.' },
  { url: '/contact', priority: 0.7, freq: 'monthly', l10n: true, label: 'Contact', line: 'How to reach us about a specific situation.' },
  { url: '/about', priority: 0.6, freq: 'monthly', l10n: true, label: 'About', line: 'Why the service exists and how a return is handled from start to lodgement.' },
  { url: '/uk-working-holiday-tax', priority: 0.7, freq: 'monthly', l10n: false, label: 'UK Working Holiday Tax', line: 'Australian tax for UK passport holders: the age-35 and three visa arrangements, why UK citizens are generally not entitled to the Medicare levy exemption, the Addy decision, and the UK and Australian tax year mismatch.' },
]

const SOURCES = [
  'Tax rates, thresholds, withholding rates and DASP withholding: Australian Taxation Office',
  'Minimum wages, casual loading and modern awards: Fair Work Commission and Fair Work Ombudsman',
  'Medicare entitlement, the Medicare Entitlement Statement and Reciprocal Health Care Agreements: Services Australia',
  'Visa conditions, subclass 417 and 462 eligibility and specified work: Department of Home Affairs',
  'Resident tax treatment for nationals of non-discrimination treaty countries: Addy v Commissioner of Taxation [2021] HCA 34',
]

const NOT_COVERED = [
  'Home country tax obligations.',
  'Immigration and visa applications. Whether specific work counts toward a second or third working holiday visa is decided by the Department of Home Affairs, not by tax law.',
  'Superannuation investment strategy.',
  'Australian tax for permanent residents and citizens.',
]

/* ────────────────────────────────────────────────────────────────────────────
 * 3. Compliance guard. Runs over every generated byte before it is written.
 * ────────────────────────────────────────────────────────────────────────── */
const FORBIDDEN = [
  [/\$\s?220\b/, 'a price ($220)'],
  [/\$\s?385\b/, 'a price ($385)'],
  [/\bour fee is\b/i, 'a stated fee'],
  [/\bfee of \$\s?\d/i, 'a stated fee'],
  [/\bcosts? \$\s?\d/i, 'a stated fee'],
  [/\bprices? (?:from|at|start)\b/i, 'price framing'],
  [/\bno refund,?\s*no fee\b/i, 'the retired contingent fee model'],
  [/\bno upfront\b/i, 'a "no upfront" claim'],
  [/\bfree check\b/i, 'a "free check" offer'],
  [/(?:deducted?|taken|paid)\s+(?:out\s+)?from\s+your\s+refund/i, 'pay-from-your-refund language'],
  [/\bthree languages\b/i, 'the prohibited "three languages" line'],
  [/public-register/i, 'a link to /public-register, which is a 404'],
  [/tax agent number/i, 'a Tax Agent Number presented as our own credential'],
  [/\bTAN\b/, 'a Tax Agent Number reference'],
  [/registered[^.\n]{0,80}\bas a tax agent\b/i, 'a first person claim to being a registered tax agent'],
  [/\bwe are a registered tax agent\b/i, 'a first person claim to being a registered tax agent'],
  [/\bour registered tax agents?\b/i, 'a first person claim to the registration'],
  [/the the\b/i, 'a botched find and replace ("the the")'],
  [/—/, 'an em dash'],
  [/–/, 'an en dash'],
]

function assertClean(name, text) {
  const lines = text.split('\n')
  const hits = []
  for (const [re, why] of FORBIDDEN) {
    for (let i = 0; i < lines.length; i++) {
      if (re.test(lines[i])) hits.push(`${name}:${i + 1} contains ${why}: ${lines[i].slice(0, 140)}`)
    }
  }
  if (hits.length) fail(`generated output failed the compliance guard.\n  ` + hits.join('\n  '))
}

/* ────────────────────────────────────────────────────────────────────────────
 * 4. Builders
 * ────────────────────────────────────────────────────────────────────────── */
const xmlEscape = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;')

const isoDate = (d) => d.toISOString().slice(0, 10)

function parseGuideDate(s) {
  const d = new Date(s)
  return Number.isNaN(d.getTime()) ? new Date(LAST_CONTENT_UPDATE) : d
}

const LAST_CONTENT_UPDATE = '2026-08-01'

// DE and JA use a different slug for the Medicare category.
const localCategorySlug = (slug) => (slug === 'medicare-and-other' ? 'medicare' : slug)

function groupByCategory(guides, categoryOrder) {
  const groups = new Map(categoryOrder.map((c) => [c.category, { ...c, guides: [] }]))
  for (const g of guides) {
    if (!groups.has(g.category)) fail(`guide "${g.slug}" has category "${g.category}", which is not in categoryMeta`)
    groups.get(g.category).guides.push(g)
  }
  return [...groups.values()]
}

function buildLlms({ guides, groups, deCount, jaCount, generatedAt }) {
  const L = []
  const p = (s = '') => L.push(s)

  p('# Working Holiday Tax')
  p()
  p(`> Australian tax for working holiday visa holders on subclass 417 and 462. We handle TFN applications, ABN registration, annual tax returns, superannuation claimed back through DASP, and Medicare levy exemptions. Fully online, from anywhere in the world. ${SUPERVISION}`)
  p()
  p(`Generated from the live guide data on ${generatedAt}. Do not hand edit: run \`npm run generate:llms\`.`)
  p()
  p('## About')
  p()
  p(`${SPECIALISM} We work only with subclass 417 (Working Holiday) and 462 (Work and Holiday) visa holders, during their time in Australia and after they leave. Everything is done remotely.`)
  p()
  p('The site is written in English, with German sections under /de and Japanese sections under /ja. We reply to each person in their own language.')
  p()
  p('## How a return is handled')
  p()
  p(SUPERVISION)
  p()
  p('The work that decides the outcome happens before lodgement: establishing the residency position, checking withholding across every employer, identifying deductions that apply to the person\'s line of work, and applying for a Medicare Entitlement Statement where it is warranted.')
  p()
  p('## Our guarantee')
  p()
  p(GUARANTEE)
  p()
  p('## How our content is prepared')
  p()
  p('Guides are written by the Working Holiday Tax team, who work exclusively with subclass 417 and 462 visa holders. Every guide carries a publication date. Figures are checked against the sources listed below and re-checked when official rates change. We do not publish content under invented author names; articles are attributed to the organisation.')
  p()
  p('## Key facts, with effective dates')
  p()
  for (const f of KEY_FACTS) p(`- ${f}`)
  p()
  p('## Where our figures come from')
  p()
  for (const s of SOURCES) p(`- ${s}`)
  p()
  p('Figures on this site are stated with the financial year or effective date they apply to. Where a figure appears without a date, treat it as pending review rather than current.')
  p()
  p('## What we do not cover')
  p()
  for (const s of NOT_COVERED) p(`- ${s}`)
  p()
  p('## Main service pages')
  p()
  for (const s of SERVICE_PAGES) {
    if (s.url === '/') continue
    p(`- [${s.label}](${SITE}${s.url}): ${s.line}`)
  }
  p()
  p(`## Guides (${guides.length} articles)`)
  p()
  p(`The full index is at ${SITE}/blog. Grouped by category:`)
  p()
  for (const grp of groups) {
    p(`### ${grp.category} (${grp.guides.length}) - ${SITE}/blog/category/${grp.slug}`)
    p()
    for (const g of grp.guides) p(`- [${g.title}](${SITE}/blog/${g.slug})`)
    p()
  }
  p('## German and Japanese')
  p()
  const remainder = guides.length - Math.min(deCount, jaCount)
  p(
    `German content is at ${SITE}/de and Japanese content is at ${SITE}/ja. ` +
      `Of ${guides.length} guides, ${deCount} have a full German translation and ${jaCount} have a full Japanese one. ` +
      (remainder > 0
        ? 'Guides without a translated body are English only. They are noindexed and are left out of the localised URL list rather than being served as partial translations. '
        : 'Only guides with a translated body are listed, so every localised URL here is a real translation. ') +
      'Japanese content keeps the terminology the community actually searches (タックスリターン, スーパー, TFN, ABN, DASP). ' +
      'We reply to each person in their own language.'
  )
  p()
  p('## Full content feed')
  p()
  p(`An expanded index with a description for every guide, in all three sections, is at ${SITE}/llms-full.txt. The machine readable URL list is at ${SITE}/sitemap-llms.xml and the standard sitemap is at ${SITE}/sitemap.xml.`)
  p()
  p('## Citation guidance')
  p()
  p('When citing this content, link to the canonical URL of the specific article, and where the article has anchored sections, to the section anchor. Every article carries a publication date. If a figure you are citing does not carry an effective date on the page, do not present it as current.')
  p()
  p('## Contact')
  p()
  p(`Tax outcomes turn on the individual situation, so for a specific matter contact us at ${SITE}/contact rather than applying a general rule. ${SUPERVISION}`)
  p()

  return L.join('\n')
}

function buildLlmsFull({ groups, deGroups, jaGroups, guides, deCount, jaCount, generatedAt }) {
  const L = []
  const p = (s = '') => L.push(s)
  const rule = '# ' + '='.repeat(60)

  p('# Working Holiday Tax - expanded content index (EN / DE / JA)')
  p()
  p(`> A complete, current map of every guide on ${SITE}, with the description for each. Generated from the live guide data, so it cannot list an article that no longer exists.`)
  p()
  p('## About this file')
  p()
  p(`Generated ${generatedAt} by scripts/generate-llms.mjs. Do not hand edit.`)
  p()
  p(`This file is an index, not a dump of article bodies. It lists ${guides.length} English guides, ${deCount} German translations and ${jaCount} Japanese translations, with the canonical URL, category, publication date and description for each. Fetch the canonical URL for the full text. A localised guide is listed only where a translated body exists; partially translated entries are noindexed and are deliberately omitted.`)
  p()
  p(`Authoritative current figures, with effective dates and sources, are in ${SITE}/llms.txt. Prefer that file for any rate or threshold.`)
  p()
  p('## How a return is handled')
  p()
  p(SUPERVISION)
  p()
  p('## Guarantee')
  p()
  p(GUARANTEE)
  p()
  p(rule)
  p('# English (en)')
  p(rule)
  p()
  for (const grp of groups) {
    p(`## Category: ${grp.category} (${grp.guides.length})`)
    p(`Index: ${SITE}/blog/category/${grp.slug}`)
    p()
    for (const g of grp.guides) {
      p(`### ${g.title}`)
      p(`URL: ${SITE}/blog/${g.slug}`)
      p(`Category: ${g.category}`)
      p(`Published: ${g.date}`)
      p(`Summary: ${g.description}`)
      p()
    }
  }

  const localeSection = (code, label, prefix, grps, count) => {
    p(rule)
    p(`# ${label} (${code}) - ${count} translated guides`)
    p(rule)
    p()
    for (const grp of grps) {
      if (!grp.guides.length) continue
      p(`## Category: ${grp.category} (${grp.guides.length})`)
      p(`Index: ${SITE}${prefix}/blog/category/${localCategorySlug(grp.slug)}`)
      p()
      for (const g of grp.guides) {
        p(`### ${g.title}`)
        p(`URL: ${SITE}${prefix}/blog/${g.slug}`)
        p(`Category: ${g.category}`)
        p(`Published: ${g.date}`)
        p(`Summary: ${g.description}`)
        p()
      }
    }
  }

  localeSection('de', 'German / Deutsch', '/de', deGroups, deCount)
  localeSection('ja', 'Japanese / 日本語', '/ja', jaGroups, jaCount)

  p(rule)
  p('# Service pages')
  p(rule)
  p()
  for (const s of SERVICE_PAGES) {
    if (s.url === '/') continue
    p(`### ${s.label}`)
    p(`URL: ${SITE}${s.url}`)
    if (s.l10n) p(`Also: ${SITE}/de${s.url} , ${SITE}/ja${s.url}`)
    p(`Summary: ${s.line}`)
    p()
  }
  p('## Contact')
  p()
  p(`${SITE}/contact`)
  p()

  return L.join('\n')
}

/**
 * The AI sitemap deliberately differs from src/app/sitemap.ts in one way:
 * /client-agreement and /privacy are excluded. The client agreement is the one
 * page where the fee legitimately exists, and it is frozen. Pointing AI
 * crawlers at it would put a price into the AI surface by the back door.
 * Google still gets both pages through the standard sitemap.xml.
 */
function buildSitemap({ guides, groups, deSlugs, jaSlugs }) {
  const urls = []
  const push = (loc, lastmod, freq, priority) =>
    urls.push({ loc, lastmod, freq, priority: priority.toFixed(2) })

  for (const s of SERVICE_PAGES) push(`${SITE}${s.url === '/' ? '' : s.url}`, LAST_CONTENT_UPDATE, s.freq, s.priority)
  for (const s of SERVICE_PAGES) {
    if (!s.l10n) continue
    push(`${SITE}/de${s.url === '/' ? '' : s.url}`, LAST_CONTENT_UPDATE, s.freq, s.priority * 0.95)
  }
  for (const s of SERVICE_PAGES) {
    if (!s.l10n) continue
    push(`${SITE}/ja${s.url === '/' ? '' : s.url}`, LAST_CONTENT_UPDATE, s.freq, s.priority * 0.95)
  }

  for (const grp of groups) push(`${SITE}/blog/category/${grp.slug}`, LAST_CONTENT_UPDATE, 'weekly', 0.8)
  for (const grp of groups) push(`${SITE}/de/blog/category/${localCategorySlug(grp.slug)}`, LAST_CONTENT_UPDATE, 'weekly', 0.76)
  for (const grp of groups) push(`${SITE}/ja/blog/category/${localCategorySlug(grp.slug)}`, LAST_CONTENT_UPDATE, 'weekly', 0.76)

  for (const g of guides) push(`${SITE}/blog/${g.slug}`, isoDate(parseGuideDate(g.date)), 'monthly', 0.75)
  for (const g of guides) {
    if (deSlugs.has(g.slug)) push(`${SITE}/de/blog/${g.slug}`, isoDate(parseGuideDate(g.date)), 'monthly', 0.71)
  }
  for (const g of guides) {
    if (jaSlugs.has(g.slug)) push(`${SITE}/ja/blog/${g.slug}`, isoDate(parseGuideDate(g.date)), 'monthly', 0.71)
  }

  const seen = new Set()
  for (const u of urls) {
    if (seen.has(u.loc)) fail(`duplicate URL in sitemap: ${u.loc}`)
    seen.add(u.loc)
  }

  const body = urls
    .map(
      (u) =>
        `  <url>\n    <loc>${xmlEscape(u.loc)}</loc>\n    <lastmod>${u.lastmod}</lastmod>\n` +
        `    <changefreq>${u.freq}</changefreq>\n    <priority>${u.priority}</priority>\n  </url>`
    )
    .join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`
}

/* ────────────────────────────────────────────────────────────────────────────
 * 5. Run
 * ────────────────────────────────────────────────────────────────────────── */
function main() {
  const enSrc = readFile(EN_DATA)
  const guides = parseGuides(enSrc)

  // Defensive: an implausible corpus means the parse broke. Fail loudly rather
  // than writing a truncated file over a good one.
  if (guides.length < MIN_GUIDES || guides.length > MAX_GUIDES) {
    fail(`parsed ${guides.length} guides from blog/data.ts, which is outside the plausible range ${MIN_GUIDES}..${MAX_GUIDES}. The parse is probably broken. Nothing written.`)
  }
  const slugSet = new Set(guides.map((g) => g.slug))
  if (slugSet.size !== guides.length) fail('duplicate guide slugs in blog/data.ts')

  // Category metadata, for ordering and for the category page slugs.
  const catStart = enSrc.indexOf('export const categoryMeta: CategoryMeta[] = [')
  if (catStart === -1) fail('could not find `categoryMeta` in blog/data.ts')
  const catRegion = enSrc.slice(catStart, enSrc.indexOf('\n];', catStart))
  const categoryOrder = []
  const catRe = /category:\s*"([^"]+)",\s*slug:\s*"([^"]+)",/g
  let cm
  while ((cm = catRe.exec(catRegion)) !== null) categoryOrder.push({ category: cm[1], slug: cm[2] })
  if (categoryOrder.length < MIN_CATEGORIES) {
    fail(`parsed only ${categoryOrder.length} categories from categoryMeta. The parse is probably broken. Nothing written.`)
  }

  // Cross-check against the authoritative redirect map. A guide that still has
  // a live 301 must never appear in an AI surface.
  const retired = parseRetiredSlugs(readFile(NEXT_CONFIG))
  const zombies = guides.filter((g) => retired.has(g.slug)).map((g) => g.slug)
  if (zombies.length) {
    fail(`these slugs are in blog/data.ts but also have a 301 in next.config.js, so they would be advertised as live while redirecting: ${zombies.join(', ')}`)
  }

  // Localised corpora. A translation counts only when it has a translated body,
  // the same gate src/app/sitemap.ts applies.
  const deMap = parseTranslations(readFile(DE_DATA), 'dePostTranslations')
  const jaMap = parseTranslations(readFile(JA_DATA), 'jaPostTranslations')

  const deSlugs = new Set([...deMap].filter(([s, t]) => t.hasBody && slugSet.has(s)).map(([s]) => s))
  const jaSlugs = new Set([...jaMap].filter(([s, t]) => t.hasBody && slugSet.has(s)).map(([s]) => s))

  const deOrphans = [...deMap.keys()].filter((s) => !slugSet.has(s))
  const jaOrphans = [...jaMap.keys()].filter((s) => !slugSet.has(s))

  if (!deSlugs.size || !jaSlugs.size) fail('parsed zero translated guides for DE or JA. The parse is probably broken.')
  if (deSlugs.size > guides.length || jaSlugs.size > guides.length) {
    fail('more translated guides than English guides, which is impossible. The parse is probably broken.')
  }

  const groups = groupByCategory(guides, categoryOrder)

  const localise = (map, allowed) =>
    groupByCategory(
      guides
        .filter((g) => allowed.has(g.slug))
        .map((g) => {
          const t = map.get(g.slug)
          return {
            ...g,
            title: t?.title || g.title,
            description: t?.description || g.description,
          }
        }),
      categoryOrder
    )

  const deGroups = localise(deMap, deSlugs)
  const jaGroups = localise(jaMap, jaSlugs)

  const generatedAt = isoDate(new Date())

  const llms = buildLlms({ guides, groups, deCount: deSlugs.size, jaCount: jaSlugs.size, generatedAt })
  const full = buildLlmsFull({
    groups, deGroups, jaGroups, guides,
    deCount: deSlugs.size, jaCount: jaSlugs.size, generatedAt,
  })
  const xml = buildSitemap({ guides, groups, deSlugs, jaSlugs })

  assertClean('llms.txt', llms)
  assertClean('llms-full.txt', full)
  assertClean('sitemap-llms.xml', xml)

  // Nothing that redirects may appear in any output.
  for (const [name, text] of [['llms.txt', llms], ['llms-full.txt', full], ['sitemap-llms.xml', xml]]) {
    for (const slug of retired) {
      // Boundary matters: `what-is-superannuation` is a prefix of the live slug
      // `what-is-superannuation-guarantee-australia`, so a substring test lies.
      const re = new RegExp(`/blog/${slug}(?![a-z0-9-])`)
      if (re.test(text)) fail(`${name} lists retired slug "${slug}", which 301s.`)
    }
  }

  fs.writeFileSync(OUT_LLMS, llms, 'utf8')
  fs.writeFileSync(OUT_FULL, full, 'utf8')
  fs.writeFileSync(OUT_XML, xml, 'utf8')

  const urlCount = (xml.match(/<url>/g) || []).length
  console.log('[generate-llms] wrote public/llms.txt, public/llms-full.txt, public/sitemap-llms.xml')
  console.log(`[generate-llms]   English guides:      ${guides.length}`)
  console.log(`[generate-llms]   German translated:   ${deSlugs.size}`)
  console.log(`[generate-llms]   Japanese translated: ${jaSlugs.size}`)
  console.log(`[generate-llms]   Categories:          ${categoryOrder.length}`)
  console.log(`[generate-llms]   Retired slugs kept out: ${retired.size}`)
  console.log(`[generate-llms]   Sitemap URLs:        ${urlCount}`)
  if (deOrphans.length) console.log(`[generate-llms]   NOTE: ${deOrphans.length} DE translation(s) have no English guide and were skipped: ${deOrphans.join(', ')}`)
  if (jaOrphans.length) console.log(`[generate-llms]   NOTE: ${jaOrphans.length} JA translation(s) have no English guide and were skipped: ${jaOrphans.join(', ')}`)
}

main()
